### PR TITLE
Update Post “2024-10-local-ancestry-inference-for-african-african-american-samples-in-gnomad”

### PR DESCRIPTION
**Pull request by phildarnowsky-broad**
Automatically generated by Decap CMS

### CODE REVIEW

**Review by klaricch — COMMENTED** [review]
Does the figure for 22-36265860-A-G also need updates?

**Comment by phildarnowsky-broad** [comment]
> 22-36265860-A-G

I'll find out

**Comment by klaricch** [comment]
> > 22-36265860-A-G
> 
> I'll find out

was just checking the browser and looks like it matches up for that one

**Review by klaricch — APPROVED** [review]

**Comment by phildarnowsky-broad** [comment]
@klaricch sounds good, I also just got confirmation from Pragati that the other figure is correct

**Pull request merged**
