### PR TITLE
Add changelog entry for gene page csv export fix

### PR DESCRIPTION
**Pull request by rileyhgrant**
Corresponding browser PR: https://github.com/broadinstitute/gnomad-browser/pull/1318

Link to preview: https://gnomad.broadinstitute.org/news/preview/148/2023-12-fix-gene-page-variants-csv/

### CODE REVIEW

**Review by ch-kr — APPROVED** [review]
this looks good to me! one small question: should this entry explain what the issue was at all?

**Comment by rileyhgrant** [comment]
Ah good thought, as in should we describe what the actual issue was?

We could certainly put that in, the gene page combined exome and genome counts locally on the page, and it was summing genetic ancestry group population counts based on index, which worked fine for every prior release but since v4 was v3 genomes and v4 exomes, the order and amount of genetic ancestry groups different for different variants, and thus would incorrectly create sums on variants that occurred in both exomes and genomes. 

Is a line saying that it was incorrectly summing genetic ancestry group counts based on position in a list sufficient? Or we could add 2-3 sentences to say more or less what was written above a little more precisely. I'm not sure how much detail makes sense.

**Comment by ch-kr** [comment]
One line sounds good to me -- it's super helpful that you've documented the issue here for future reference, but a high level explanation of the issue in the changelog should be enough detail

**Comment by rileyhgrant** [comment]
Great, thanks as always KC :)

**Pull request merged**
